### ISSUE TITLE
Looper v2 docs suggestions

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepspec#36]
@donaldcampbelljr can you take care of this first round of docs suggestions?

- [x] - combine all quickstart into a single tutorial, which will be the first item under "Pipeline User Guide" (instead of its own QuickStart main section). This would be a jupyter notebook. Right now almost all of them are already in jupyter, but you might need to integrate the first markdown into the notebook to get these all into one page.
- [x] - merge "Defining a project" and "Details of a project" into one explaination of how to define a project.
- [x] - merge "Running a pipeline" and "Parameterizing pipelines"
- [x] - Maybe also merge "Running multiple pipelines" (from the developer guide) into the "Running a pipeline". I think this is user docs, and really just shows how to run pipelines.  (See if you agree).
- [x] - In "Defining looper config" -- add a comment/section to say you can start with `looper init` to create one for you.
- [x] - In "Defining looper config", add an introduction that explains *what a looper config is*, and that it lives at `.looper.yaml` by default.
- [x] - I'm wondering if "Defining looper config" should be integraetd with the "Run your own project -> Initialize looper" docs -- these seem to be really be explaining the same thing but in slightly different ways. Could probably be streamlined into one?

**Comment by nsheff** [comment]
I've just pushed a few changes to your branch, so make on top of my initial changes

**Comment by donaldcampbelljr** [comment]
Ok, all but the first items have been addressed. I was hesitant to squash too much into one section and make it _less_ digestible to new users.
